script:
  novita_fan_power:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: fan
          command: power
  novita_fan_oscillate1:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: fan
          command: oscillate1
  novita_fan_faster:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: fan
          command: faster
  novita_fan_slower:
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: fan
          command: slower
