input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Room
      - Living Room
      - Room 1
      - Room 2
    initial: Select Room

sensor:
  - platform: template
    sensors:
      vacuum_status:
        friendly_name: "Vacuum Status"
        value_template: "{{ state_attr('vacuum.roborock_vacuum_s5', 'status') }}"

automation:
  - id: vacuum_room
    alias: Vacuum Room
    trigger:
    - platform: state
      entity_id: input_select.vacuum_room
      from: 'Select Room'
    action:
    - service: vacuum.send_command
      data_template:
        entity_id: vacuum.roborock_vacuum_s5
        command: app_zoned_clean
        params: >
          {% if is_state('input_select.vacuum_room', 'Living Room') %}
            [[20500,25000,23750,32500,1]]
          {% elif is_state('input_select.vacuum_room', 'Room 1') %}
            [[23500,30500,27500,34750,1]]
          {% elif is_state('input_select.vacuum_room', 'Room 2') %}
            [[23500,25000,30500,26500,1]]
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.vacuum_room
      data_template:
        option: "Select Room"
