- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

- platform: time_date
  display_options:
    - 'date_time'
    - 'time'

- platform: mitemp_bt
  name: Living Room
  mac: '4c:65:a8:d5:c0:f8'
  cache_value: 600
  monitored_conditions:
    - temperature
    - humidity

- platform: xiaomi_miio
  name: Air Quality Monitor
  host: 192.168.1.10
  scan_interval: 60
  token: !secret mi_aqsensor_token

- platform: huesensor

- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  # If errors occur, remove degree symbol below
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 200

# Dummy sensor to allow secrets in template
- platform: template
  sensors:
    workout_media_url:
      value_template: !secret workout_media_url
    clock_media_baseurl:
      value_template: !secret clock_media_baseurl
