light.all_lights:
  hidden: true
light.bedroom_1:
  hidden: true
light.bedroom_2:
  hidden: true
light.entertainment_area_1:
  hidden: true
light.lamp_1:
  friendly_name: Lamp 1 (Wall)
light.lamp_2:
  friendly_name: Lamp 2 (Stand)
  icon: mdi:floor-lamp
light.lamp_3:
  friendly_name: Lamp 3 (Table)
  icon: mdi:checkbox-blank-circle
light.lamp_4:
  friendly_name: Lamp 4 (Wall)
light.lightstrip:
  icon: mdi:led-strip
light.floor_light:
  icon: mdi:led-strip
light.room_1_lights:
  icon: mdi:bed-empty
light.room_2_lights:
  icon: mdi:bed-empty
sensor.date_time:
  hidden: true
sensor.time:
  hidden: true
script.room1_7min_workout:
  icon: mdi:dumbbell
script.room2_7min_workout:
  icon: mdi:dumbbell
automation.room_1_motion_detection:
  icon: mdi:animation
automation.room_2_motion_detection:
  icon: mdi:animation
