homeassistant:
  customize:
    script.room1_tv_source:
      icon: mdi:video-input-hdmi
    script.room1_tv_vol_down:
      icon: mdi:volume-minus
    script.room1_tv_vol_up:
      icon: mdi:volume-plus

switch:
  - platform: template
    switches:
      room1_tv:
        friendly_name: Samsung TV
        value_template: "{{ is_state('device_tracker.room1_tv', 'home') }}"
        turn_on:
          service: remote.send_command
          data:
            entity_id: remote.room1
            device: tv
            command: power
        turn_off:
          service: remote.send_command
          data:
            entity_id: remote.room1
            device: tv
            command: power

input_select:
  room1_tv_channels:
    name: TV Channel
    icon: mdi:grid
    options:
    - "Select Channel"
    - "Channel 5"
    - "Channel 8"
    - "Channel NewsAsia"
    - "Channel U"
    initial: "Select Channel"

script:
  'room1_tv_source':
    alias: Select Source
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: tv
          command: source
  'room1_tv_vol_up':
    alias: Volume Up
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: tv
          command: volume up
  'room1_tv_vol_down':
    alias: Volume Down
    sequence:
      - service: remote.send_command
        data:
          entity_id: remote.room1
          device: tv
          command: volume down

automation:
  - id: room1_tv_channels
    alias: Room 1 TV Channels
    trigger:
    - platform: state
      entity_id: input_select.room1_tv_channels
    condition:
    - condition: template
      value_template: "{{ not is_state('input_select.room1_tv_channels', 'Select Channel') }}"
    action:
    - service: remote.send_command
      data_template:
        entity_id: remote.room1
        device: tv
        command: >
          {% if trigger.to_state.state == 'Channel 5' %}
            channel5
          {% elif trigger.to_state.state == 'Channel 8' %}
            channel8
          {% elif trigger.to_state.state == 'Channel NewsAsia' %}
            cna
          {% elif trigger.to_state.state == 'Channel U' %}
            channelu
          {% endif %}
    - delay:
        milliseconds: 200
    - service: input_select.select_option
      data:
        entity_id: input_select.room1_tv_channels
        option: Select Channel
