homeassistant:
  customize:
    script.room1_tv_source:
      icon: mdi:video-input-hdmi
    script.room1_tv_vol_down:
      icon: mdi:volume-minus
    script.room1_tv_vol_up:
      icon: mdi:volume-plus

switch:
  - platform: template
    switches:
      room1_tv:
        friendly_name: Samsung TV
        value_template: "{{ is_state('device_tracker.room1_tv', 'home') }}"
        turn_on:
          service: broadlink.send
          data:
            host: 192.168.1.112
            packet:
              - "JgBGAJWVEzcTNxM3ExMSExITEhMSExI4EjgSOBMSExITEhMSExITEhM3ExMSExI4EhMSExITEjgTEhM3EzcTEhM3EzgSOBIADQUAAA=="
        turn_off:
          service: broadlink.send
          data:
            host: 192.168.1.112
            packet:
              - "JgBGAJaUEzgSOBI4ExITEhMSExITEhM4EjgSOBITExITEhMSExITEhM4EhMSExITEhMSExMSEzcTEhM3EzgSOBI4EzcTNxMADQUAAA=="

input_select:
  room1_tv_channels:
    name: TV Channel
    icon: mdi:grid
    options:
    - "Select Channel"
    - "Channel 5"
    - "Channel 8"
    - "Channel NewsAsia"
    - "Channel U"
    initial: "Select Channel"

script:
  'room1_tv_source':
    alias: Select Source
    sequence:
      - service: broadlink.send
        data:
          host: 192.168.1.112
          packet:
            - "JgBGAJOXETkROhA6EBUQFRAVEBUQFRA6EDoROREUERUQFRAVEBUQOhAVEBUQFRAVEBUQFREUERQRORE6EDoQOhA6EDoQOhEADQUAAA=="
  'room1_tv_vol_up':
    alias: Volume Up
    sequence:
      - service: broadlink.send
        data:
          host: 192.168.1.112
          packet:
            - "JgBGAJOXETkROhA6EBUQFRAVEBUQFRA6EDoROREUERUQFRAVEBUQOhA6EDoQFRAVEBURFBITEhMSExEVEjgSOBI4EjgSOBIADQUAAA=="
  'room1_tv_vol_down':
    alias: Volume Down
    sequence:
      - service: broadlink.send
        data:
          host: 192.168.1.112
          packet:
            - "JgCMAJSWEjgSORE5ERQRFBEUERQRFBE5ETkSOBITEhMSFBEUERQQOhE5ERQQOhEUEBURFBEUERQRFBE5ERUQOhA6EDoQOhAABg=="

automation:
  - id: room1_tv_channels
    alias: Room 1 TV Channels
    trigger:
    - platform: state
      entity_id: input_select.room1_tv_channels
    condition:
    - condition: template
      value_template: "{{ not is_state('input_select.room1_tv_channels', 'Select Channel') }}"
    action:
    - service: broadlink.send
      data_template:
        host: 192.168.1.112
        packet: >
          {% if trigger.to_state.state == 'Channel 5' %}
            JgBGAJSVEzgSOBM3ExISExIUEhMRFBI4EjgSOBITEhMSExITExITNxMTEjgSExEUEhMSExEUERQRORITEjgSOBI4EjkRORIADQUAAA==
          {% elif trigger.to_state.state == 'Channel 8' %}
            JgBGAJWVEzcTNxM4EhMSExITEhMSExI4EjgSOBMSExITExITEhMSExI4EjgSExITEhMSExITEzcTEhMTEjgTNxI4EjgSOBIADQUAAA==
          {% elif trigger.to_state.state == 'Channel NewsAsia' %}
            JgBGAJSXEDoQOhE5ERQRFRAVEBUQFRA6EDoROREUERUQFRAVEBUQFRA6ERQROREVEBUQFRAVEDoQFRA6ERQRORE6EDoQOhAADQUAAA==
          {% elif trigger.to_state.state == 'Channel U' %}
            JgBGAJSXEDoQOhA6ERQRFBEUERUQFRA6EDoQOhEUERQRFBEVEBUQFRAVEDoQOhAVERQRFBEUEToQOhAVEBUQOhE5ETkROhAADQUAAA==
          {% elif trigger.to_state.state == 'okto' %}
            JgBGAJOXEToRORA6EBUQFRAVERQRFBE5EToQOhAVEBUQFRAVERQROREVEDoQOhAVEBUQFREUERQROREVEBUQOhA6ETkROREADQUAAA
          {% endif %}
    - delay:
        milliseconds: 200 
    - service: broadlink.send
      data:
        host: 192.168.1.112
        packet: JgBGAJaUEzgSOBI4ExITEhMSExITEhM3EzgSOBITEhMSExITExITEhMSExITNxMTEjgSOBITEjgTNxM3ExITNxMTEhMSOBIADQUAAA==
    - service: input_select.select_option
      data:
        entity_id: input_select.room1_tv_channels
        option: Select Channel
